### ISSUE TITLE
video resources

### ISSUE THREAD

**Issue by rhmunna143** [SahebRana/SahebRana#2]
![[maxresdefault](https://www.youtube.com/live/nbzvNKAd1As?si=2YjWRtRNBjFvRKq_)](https://github.com/SahebRana/SahebRana/assets/66863042/5a68a895-1fb9-4efa-a86b-8cbf9fb1bec1)

![[maxresdefault (1)](https://youtu.be/eWRfhZUzrAc?si=-qLgICRqs5KEKmau)](https://github.com/SahebRana/SahebRana/assets/66863042/11f77d33-c324-42f7-b434-f19be4e4a15a)

**Comment by SahebRana** [comment]
Got all
